[package]
name = "linked_devices_types"
version = "0.1.0"
edition = "2021"

[dependencies]
hdi = { workspace = true }
serde = "1"

[dev-dependencies]
fixt = "0.3"
hdi = { workspace = true, features = [ "test_utils"] }
